### ISSUE TITLE
Function convert_date_to_day_first - should this be added to the FuncLib?

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1269]

**Comment by C-Love** [comment]
This function is for formatting a date when we are adding it to notices in other languages with different date conventions. It is pretty specific to the On Demand process because that's the only non-English notice functionality we support.

I think either way, it is pretty process specific and I don't know where else we would ever use this, but we do have a number of scripts to support On Demand work.
