### ISSUE TITLE
Ex Parte - Phase 2 - Display and CASE NOTE Ex Parte Information/Determination 

### ISSUE THREAD

**Issue by MDR22** [Hennepin-County/MAXIS-scripts#1310]
- [ ] Display known ex parte and case information for phase 2
- [ ] Add navigation and policy/instructions
- [ ] CASE NOTE ex parte _IF NOT_ approved in Phase 2
- [ ] Confirm updates to REVW to catch in the next REVW cycle

**Comment by C-Love** [comment]
First step is to create functionality to document Not Ex Parte at Phase 2 that can be incorporated into HC Eval. This should be a dialog with inputs to document why the case cannot be approved as Ex Parte and what month the renewal will be rescheduled for.  This information will need to be entered into CASE/NOTE. 

Development of this functionality is the only thing that can happen at this point since we are waiting for instruction from DHS on this work, but we know that a CASE/NOTE will be needed.

Once this functionality is ready and we get more information from DHS, we will connect the outputs to the Data Table and make sure that the script can identify that it is a Phase 2 Ex Parte case. We will also need to update Elig Summ.

**Comment by C-Love** [comment]
This work was completed only in:
Eligibility Summary
Plus a PROBLEM button for cases that could not be approved. 

Work will continue on this issue in #1385
