### ISSUE TITLE
NOTES - CAF: Add option to add DHS-2128 form for Housing Support renewals

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1378]
[RECERTIFICATION PROCESS (state.mn.us)](https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=cm_000906) - Policy for using DHS-2128 LTC renewal for Housing Support program renewals.

**Comment by C-Love** [comment]
This is complicated because this form cannot be used for all programs. We need to create some clear logic and understanding of how this form operates and what we can do to support it.

In discuss at next meeting to try to make a plan for answering the questions:

- What happens when the form is received and there is an unsupported program?
- Is it only a problem if the program is pending or at renewal?
- What is the scope of this issue? How many of these forms are we seeing?

**Comment by C-Love** [comment]
Plan 1 - to get us started.
1. Add the form
2. IF any other cash program (other than GRH) or SNAP is active and at renewal for this form selected the script will stop
3. Message will alert the worker that policy on using this form for other recert programs is a problem and PQ is needed. 

This will be a simple update but not supportive of confusing situations.

**Comment by C-Love** [comment]
This is in place, no errors reported. Done.
