### ISSUE TITLE
PF11 Script - add option for HC REVW Dates need update

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#168]
This is based on OneSource - https://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=ONESOURCE-COVID003

Basically if the REVW HC Dates cannot be updated by the procedure outlined, a PF11 has to be sent requesting MNIT to update.

Question out to Jen on other actions we may need to take.

**Comment by MiKaylaH22** [comment]
Here is the basic detail. 

1.	Do not update REVW for the HC area. 
2.	Sometimes the STAT REVW panel will force you to update REVW for any program if the dates are old, or wrong in some way. If this is the case, OneSource has specifics on how to update correctly as to not cause other issues for the HC continuation as there are no HC reviews.
a.	IR REVW or AR REVW - If the date is current or past, change it to 12 months from the date.
b.	ER REVW – if the date is current or past, change it to 6 months from the date.
**c.	If there is an inhibiting edit when trying to save the information on this panel, send a PF11 for MNIT to update the review date: 
i.	Keywords: Last Review Date Edit
ii.	Problem Description: Cannot Update HC REVW Date
iii.	Review SIR Email for a response when this process is complete.
d.	Navigate to HC/ELIG via DAIL and review the new HC Elig results.** 
i.	If HC Elig results in an equal or better benefit set or reduced cost sharing or premiums, approve all results from the new review month onward in MAXIS. 
ii.	FIAT any failed person tests to PASSED, if needed.
e.	Update MMIS. 
f.	note all actions including COVID in the subject line and any FIAT used to approve the change. 
This information can be found directly in OneSource:

**Comment by IlseFerris** [comment]
Currently reviews are not a thing for SNAP/CASH programs. This is no longer needed this quarter. Changed the milestone. Will review in Q1 2021.

**Comment by MiKaylaH22** [comment]
For cases processed before or on the 15th of the month prior to the review month, update the next renewal dates for six months and one year later. For example, if there is a CSR for 4/22 being processed on 3/14/22 and a recertification for 05/22, set the next CSR review date for 10/22 and the next recertification review date for 04/22. If the system will not allow extending the recertification date, submit a PF11. Indicate these actions were done in the recertification CASE/NOTE. 
**reopening this one and updating to support all renewal dates that cannot be adjusted**
Also adding a provision under b -  ii that says:
Send the case through background and approve the new ELIG results so that the case does not auto-close. In the example above, this would be completed so the case does not auto-close for 05/22. If the system will not allow extending the recertification date, submit a PF11. 
iii. CASE/NOTE all actions taken on the case.

**Comment by IlseFerris** [comment]
Closing as won't fix. The scope of this is limited, and no requests have occurred.
