### ISSUE TITLE
Add Case Transfer reminder to NOTES - APPLICATION RECEIVED

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#1804]
Request by HSS, HA, to have reminder to staff regarding transferring notifications in ECF Next prior to transferring cases if necessary based on the logic already in place for the Case Assignment team.

**Comment by C-Love** [comment]
A couple of thoughts on this issue, so that we can support this requirement as much as possible. 
1. Change the verbiage to transfer the 'notifications'. Clarification on this is needed. I thought MMcG and HF have indicated that the transfer is specific to the notifications and are not around the case itself. 
2. Possibly update the input for this process to require a number of the notifications that were transferred. This may increase the engagement in this input and increase the effectiveness of this functionality.
3. Possibly add a read out of the previous caseload number (which may be the one it is in or the one it was inactive in) this will improve their ability to find the right place in ECF. This also might tell us more about when this is not necessary (previous PW is blank or out of county).
4. We also may want to add tracking of these entries, as a cookie. 

We also need to confirm with HA when they are able to implement and test the process to ensure this update supports their work.

**Comment by C-Love** [comment]
DaNM - recommend that we close this issue for now. 

CA has not been given additional guidance on this process and they are not currently doing it. 

There are some technical issues here. HA has agreed to reach out if this is brought back to the team.

**Comment by C-Love** [comment]
Partial fix is in place. Additional process may come in the future - we will create a new issue when that happens.
