### ISSUE TITLE
BULK Update of CSES for MFIP

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#205]
Process CSES messages to clear and update UNEA on MFIP cases. 
We can probably do this thing, BUT we need to ensure that it is clear NO OTHER ACTION IS BEING ACCOUNTED FOR.
We need to find a way to ensure we don't take action on cases that have other things happening. (HRF or REVW due would update and not approve)

**Comment by C-Love** [comment]
Updates of UNEA information based on CSES messages can be BULKed out. 

We have 3 types of MFIP cases to accomodate CSES:
- Cases with a HRF or REVW due that are RETRO budgeted
- Cases that are RETRO budgeted with NO HRF or REVW Due
- Cases that are prospectively budgeted. 

We can update UNEA for most of these cases all the time but need to determine next step actions. The easiest is for cases with a HRF or REVW due as no additional steps are needed because processing on these forms is still required.

Need a process map on this.

**Comment by C-Love** [comment]
The juice is not worth the squeeze.
