### ISSUE TITLE
Update TAGS in COMPLETE LIST OF SCRIPTS/SharePoint Online

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#262]
Tags will need to be determined, added to the Complete List of Scripts, and added to SharePoint Online. The following scripts are missing tags: 

- ACTIONS - JOB CHANGE REPORTED 
- NOTES - DISASTER FOOD REPLACEMENT
- UTILITIES - CONTACT KNOWLEDGE NOW
- UTILTIES - LOST APPLY MN
- UTILITIES - REPORT TO BZST
- UTILITIES - UPDATE CHECK DATES
- UTILITIES - WAIVED ER INTERVIEW SCREENING

**Comment by C-Love** [comment]
Adding a new tag - 'SUPPORT'. 
Support tag would be for scripts that request help and has an element of follow up. (ex - all the email QI scripts, PF11...)
This is separate from Utility because a utility can be used independently as a tool in your case work but doesn't need help from an outside source.

**Comment by MiKaylaH22** [comment]
Completed on SharePoint, will be discussed at next meeting.
