### ISSUE TITLE
Scripts to Support DHS Requirements

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#266]
On our SharePoint 'Best Practices Using BlueZone Scripts' page, we have a section with scripts that support specific policy and procedural information and for which program. This is partial list and this work needs to continue in 2021.

**Comment by IlseFerris** [comment]
Changing issue from research project to updating the information in the scripts themselves. In our project's closing documentation there is an assessment for finding the policy and procedures. Variables will be added to CLoS and output into UTILTIES - ALL SCRIPT for staff to access, 

Will set up coordination meeting in Q4 2021.

**Comment by C-Love** [comment]
This update should be stored in the 'Complete List of Scripts'. We need to add parameters to the Complete List of Scripts so that we can programmatically pull and assess this information. Each script would have information stored about itself within the Complete List of Scripts that can be added to the All Scripts and output to Excel for access by all users. 

Steps to take:

- [ ] Update Complete List of Scripts - decide on additional parameters (one as a boolean to indicate IF a script helps to support DHS requirements and then an array OF the actual resources that is supports)
- [ ] Evaluate the scripts and update the Complete List of Scripts for each script.
- [ ] Update the All Scripts script to output information into the dialog about meeting a DHS requirement and then output the specific resources into the Excel. This will need logic to determine if the reference in the array is a URL or not for proper display.

**Comment by IlseFerris** [comment]
#841 is the active work. This is a duplicative issue at this point. Closing.
