### ISSUE TITLE
Update to NOTES - SMRT to match new State Requirements

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#51]
The state has updated the requirements for a SMRT referral. We will update the script NOTES - SMRT to handle for these updates. 

1. MA must be active or pending to submit a SMRT referral. Add a dropdown to both the 'Initial request' and 'ISDS Referral Completed' dialogs to indicate if this person is active or pending MA.
2. Must check SMI for disability determination FIRST. Add droplist that worker needs to indicate SMI has been reviewed.
3. Get an image of the ECF referral form and the ISDS Referral so we can be sure all the correct items are added. Mostly looking at 'Programs Requested'.
4. If this is for a waiver the MN Choices assessment completion date or scheduled date will need to be entered/captured.
5. We may need a better way to track these to ensure the pending MA cases aren't denied and referrals aren't refused. Sent Email to Shannon Stockdale about counts.

**Comment by C-Love** [comment]
Add Redirect to the MC Menu to access the NOTES - SMRT script.

Add changelog to NOTES - SMRT to request report for any updates desired.

Add in script error reporting to NOTES - SMRT to get more ideas and enhancements for this script.

**Comment by MiKaylaH22** [comment]
Question was asked by KNC - MA must be active or pending to submit a SMRT referral - where did this information come from?

**Comment by MiKaylaH22** [comment]
This information came from HC policy Meeting 2019 and the parts that are documented are the parts that we will support.

**Comment by MiKaylaH22** [comment]
- [ ] Must check SMI for disability determination FIRST.  
- [ ] Ask the question of is client pending or active on MA? since it is not documented but we know it is needed. 
- [ ] Add droplist that worker needs to indicate SMI has been reviewed.
- [ ] Get an image of the ECF referral form and the ISDS Referral so we can be sure all the correct items are added. Mostly looking at 'Programs Requested'.
- [ ] If this is for a waiver the MN Choices assessment completion date or scheduled date will need to be entered/captured.
- [ ] We may need a better way to track these to ensure the pending MA cases aren't denied and referrals aren't refused. 
- [ ] If the reason is not listed, call SMRT at 800-235-7396 or 651-431-2493 to get approval. 
REMEMBER  to Check the box next to SMRT Approved and add a comment before submitting the referral.

**Comment by MiKaylaH22** [comment]
Would it be possible to do the following to the NOTES > SMRT > Determination Received:
1.	Add a field for “Why was SMRT requested?” - can do because it aligns with matching ISDS
2.	Change the “Approved programs” to “Current MA eligibility”? - may have actions needed on other programs -WHAT ARE WE TRYING TO UNDERSTAND what programs will be impacted by this person being certified disa?
3.    Confirm that in maxis or mets we need to ensure that the person is trying to apply for assistance

**Comment by MiKaylaH22** [comment]
1. Add a field for “Why was SMRT requested?” - can do because it aligns with matching ISDS
2. Change the “Approved programs” to “Current MA eligibility”? 
Q) may have actions needed on other programs? 
Q) what programs will be impacted by this person being certified disa?
3. Confirm that in maxis or mets we need to ensure that the person is trying to apply for assistance

**Comment by IlseFerris** [comment]
@C-Love will connect with Knowledge Coordinator around bottleneck in process and gather information for moving this forward.

**Comment by C-Love** [comment]
New workflow for this script to support the Hennepin process and DHS process.

There are 3 actions associated with this work and the documentation needs should be focused on the case documentation requirement. 

1. Initial request to the agency by resident or resident representative. This could be taken by any eligibility worker. The details of the SMRT request and person information related to the request should be documented in CASE/NOTE here and will also be entered into an ECF workflow to be directed to a worker with ISDS access. 
2. Workers with ISDS access will confirm and enter the information from the ECF form into ISDS. We must document the entry date and any updates to the information detailed in the form. 
3. A decision will be sent to the agency and that determination needs to be entered into CASE/NOTE as well as checking DISA for accuracy.

Information about this process is in HSR Manual  [State Medical Review Team (SMRT) (sharepoint.com)](https://hennepin.sharepoint.com/teams/hs-es-manual/SitePages/State_Medical_Review_Team_(SMRT).aspx)

Initial Request
1. Worker enters CASE Number
2. Script pulls person list using case number 
4. SMRT requested for will be a ComboBox selection of persons listed on the case
5. The script will then pull the age for the person - if the selected person is on the case otherwise the worker will need to enter the age.
6. The additional detail will appear in the final dialog for all the selection information
7. CASE/NOTE to be entered

Enter into ISDS 
1. Worker enters CASE Number
2. Script will read CASE/NOTE for a SMRT Initial Request to fill in the data about the request
3. If data is NOT found the worker will need to enter the information based on the process in the initial request
4. If data is found the worker will confirm it is accurate and update any detail that is needed
5. The worker will submit the information in ISDS and document the date the SMRT was submitted
6. CASE/NOTE the information was submitted

Decision Received
1.  Worker enters CASE Number
2. Script will read CASE/NOTE for a SMRT Initial Request to fill in the data about the request
3. Script will read DISA information and try to autofill information
4. Worker will confirm the decision (approved/denied) and the start and end dates of the SMRT certification
5. Script will CASE/NOTE and advise that additional review and action may be needed
6. Possible DISA update functionality

**Comment by C-Love** [comment]
We need to add a withdraw option.
