### ISSUE TITLE
PMI Merge CASE NOTE Script to document a PMI Merge request sent in SIR

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#736]
Need to pull the CASE NOTE portion of the PF11 Action script for PMI Merges. They can no longer be sent via PF11 but for a MX case, we still need to create the NOTE. 

Currently process direction is being created and once complete we will be able to design a script to support this action. Knowledge Coordinator is currently working on this process.

This is associated with #713 in it is for after the Merge Request has been sent and #713 is to support the discovery on the merge request prior to sending it.

**Comment by IlseFerris** [comment]
JA sent some feedback. His question for us is how long does it take for workers to get the task number from DHS via SIR. MH will sent to him. 

Here's his feedback: 
So DHS has provided no case noting requirements for PMI merges (at least that I could find in SIR or POLI/TEMP). And yeah, having a script for this may be unnecessary altogether because the script wouldn’t be doing anything other than leaving a case note, is that what you mean by having a one to one entry?

But if we want one, I think what you have is good, but technically has some fields that really aren’t needed (imo). Asking for associated case numbers I don’t think is necessary, since PMI numbers are person specific and I’m pretty sure once merged all those cases will show up when searching that person. Reason for request is not needed since that reason should always be “because they have duplicate PMIs”. I would recommend the following:

PMI merge request for CLIENT’S NAME (header)
Current PMI:
Duplicate PMIs:
Marked as Urgent: Y or N
Date request was sent:
Task number received via SIR email:

That being said I am checking to see if I can find some recent examples of PMI merges so we can see how quickly workers receive the SIR email response to their request. If it is not immediate I would hesitate to require this for the case note since I would rather the workers note the action the moment it’s done instead of waiting to come back to it when they get around to it….in which case I would also remove date of request as that would presumably be the date they case noted it. I’ll let you know what I find out.

**Comment by IlseFerris** [comment]
Closing as a won't fix.
