### ISSUE TITLE
NOTES - APPLICATION RECEIVED: Randomization for basket selection

### ISSUE THREAD

**Issue by IlseFerris** [Hennepin-County/MAXIS-scripts#742]
Adults EXP SNAP baskets will be randomized (EX1 and EX2).

These baskets are ready now.

**Comment by C-Love** [comment]
I have big concerns with the EGA automation. We have not been adding any emer baskets to the script automation because we do not have the clarity about prioritization or documentation on how EA vs EGA are being pended. 

Additionally, prioritizing EGA over EXP voids efforts in using the EXP baskets as priority assignments.
