### ISSUE TITLE
ACTIONS - TRANSFER CASE: Multiple bugs 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#928]
Problem: 
When a user tries to transfer a case into their own X127 the script inhibits this 
Resolution: 
Check for if they are trying to xfer to themselves and if so do not check the worker number on STAT/SELF menu

**Comment by MiKaylaH22** [comment]
Problem: 
Cases are getting Locked in background and cant be completed 
Resolution:
Adding messaging to the "success" message to remind workers to check if the case is stuck adding verbiage to the script run low-down

**Comment by IlseFerris** [comment]
Consolidating bugs here: 

- [ ] Cases are getting locked in background. Since transferring a case should be one of the last steps, will add reminder to closing message to review/approve results and work DAIL's prior to the transfer
- [ ] Script inhibits staff from transferring cases into their own number. 
- [ ] Excluded time cases are asked to enter a date to change the county of financial responsibility.

**Comment by IlseFerris** [comment]
Script has been in end-user testing in two weeks with no issues reported. Closing issue.
